- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobBlueshieldMaid

- type: playTimeTracker
  id: JobNanotrasenRepresentative

- type: playTimeTracker
  id: JobMagistrate
